name: Coffee4j PR CI
on:
  pull_request_target:
    branches: [ "main" ]
jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
      - name: Build with Maven
        run: mvn -B package --file pom.xml